import type { Flavor, Product, DipOption, SideOption, DrinkOption } from "@/types/shop";

export const FLAVORS: Flavor[] = [
  {
    id: "lemon-pepper",
    name: "Lemon Pepper",
    slug: "lemon-pepper",
    heatLevel: 1,
    description: "Sabor cítrico crujiente con toque de pimienta negra molida. El favorito indiscutible.",
    isDryRub: true,
    badge: "Más Vendido",
  },
  {
    id: "garlic-parmesan",
    name: "Garlic Parmesan",
    slug: "garlic-parmesan",
    heatLevel: 0,
    description: "Mantequilla de ajo rostizado con auténtico queso parmesano italiano.",
    isDryRub: true,
    badge: "Favorito",
  },
  {
    id: "hawaiian",
    name: "Hawaiian",
    slug: "hawaiian",
    heatLevel: 0,
    description: "Salsa dulce frutal inspirada en piña caribeña y especias asiáticas suaves.",
    isDryRub: false,
  },
  {
    id: "hickory-bbq",
    name: "Hickory Smoked BBQ",
    slug: "hickory-bbq",
    heatLevel: 1,
    description: "Notas dulces y ahumadas a madera de nogal con consistencia rica y caramelizada.",
    isDryRub: false,
  },
  {
    id: "spicy-korean",
    name: "Spicy Korean Q",
    slug: "spicy-korean",
    heatLevel: 2,
    description: "Gochujang picante dulce con toques de sésamo tostado y jengibre fresco.",
    isDryRub: false,
    badge: "Nuevo",
  },
  {
    id: "louisiana-rub",
    name: "Louisiana Rub",
    slug: "louisiana-rub",
    heatLevel: 2,
    description: "Sazonador seco estilo cajún sureño con notas de pimentón, ajo y orégano.",
    isDryRub: true,
  },
  {
    id: "original-hot",
    name: "Original Hot",
    slug: "original-hot",
    heatLevel: 3,
    description: "La salsa búfalo clásica de Wingstop que lo inició todo. Picor vinagrado perfecto.",
    isDryRub: false,
    badge: "Clásico",
  },
  {
    id: "mango-habanero",
    name: "Mango Habanero",
    slug: "mango-habanero",
    heatLevel: 4,
    description: "Aroma frutal dulce de mango tropical que explota con el fuego puro del habanero.",
    isDryRub: false,
    badge: "Picoso Top",
  },
  {
    id: "atomic",
    name: "Atomic",
    slug: "atomic",
    heatLevel: 5,
    description: "Nuestra salsa más extrema con chile fantasma y habanero ultra concentrado. Solo para valientes.",
    isDryRub: false,
    badge: "Nivel 5 🔥",
  },
];

export const DIPS: DipOption[] = [
  { id: "ranch", name: "Ranch Hecho en Casa (2 oz)", price: 25 },
  { id: "blue-cheese", name: "Blue Cheese Artesanal (2 oz)", price: 29 },
  { id: "honey-mustard", name: "Honey Mustard Dulce", price: 25 },
  { id: "queso-cheddar", name: "Dip de Queso Cheddar Caliente", price: 32 },
];

export const SIDES: SideOption[] = [
  { id: "papas-sazonadas", name: "Papas Fritas Sazonadas Wingstop (Regulares)", price: 65 },
  { id: "papas-queso", name: "Papas Bañadas en Queso Cheddar y Jalapeño", price: 89 },
  { id: "veggie-sticks", name: "Veggie Sticks Frescos (Zanahoria y Apio)", price: 39 },
  { id: "aros-cebolla", name: "Aros de Cebolla Crujientes", price: 79 },
];

export const DRINKS: DrinkOption[] = [
  { id: "coca-cola-600", name: "Coca-Cola Original 600 ml", price: 38 },
  { id: "coca-sin-azucar", name: "Coca-Cola Sin Azúcar 600 ml", price: 38 },
  { id: "sprite-600", name: "Sprite 600 ml", price: 38 },
  { id: "te-helado", name: "Té Helado de Limón Refill", price: 42 },
  { id: "cerveza-artesanal", name: "Cerveza Corona Extra 355 ml", price: 55 },
];

export const PRODUCTS: Product[] = [
  {
    id: "prod-alitas-10",
    name: "Alitas Tradicionales (10 Pzas)",
    slug: "alitas-10-piezas",
    description: "10 alitas de pollo frescas con hueso, bañadas o sazonadas a mano con hasta 2 sabores de tu elección.",
    basePrice: 199,
    category: "alitas",
    piecesCount: 10,
    maxFlavorsAllowed: 2,
    imageUrl: "https://images.unsplash.com/photo-1567620832903-9fc6debc209f?q=80&w=800&auto=format&fit=crop",
    popular: true,
  },
  {
    id: "prod-alitas-15",
    name: "Alitas Tradicionales (15 Pzas)",
    slug: "alitas-15-piezas",
    description: "15 alitas clásicas doradas al momento con hasta 2 sabores y aderezo a elegir.",
    basePrice: 289,
    category: "alitas",
    piecesCount: 15,
    maxFlavorsAllowed: 2,
    imageUrl: "https://images.unsplash.com/photo-1527477396000-e27163b481c2?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: "prod-alitas-20",
    name: "Alitas Tradicionales (20 Pzas)",
    slug: "alitas-20-piezas",
    description: "20 alitas crujientes con hueso, ideales para compartir. Elige hasta 3 sabores distintos.",
    basePrice: 379,
    category: "alitas",
    piecesCount: 20,
    maxFlavorsAllowed: 3,
    imageUrl: "https://images.unsplash.com/photo-1608039829572-78524f79c4c7?q=80&w=800&auto=format&fit=crop",
    popular: true,
  },
  {
    id: "prod-boneless-10",
    name: "Boneless de Pechuga (10 Pzas)",
    slug: "boneless-10-piezas",
    description: "10 bocados de 100% pechuga de pollo empanizada y bañada en tus salsas preferidas. Cero huesos, máximo sabor.",
    basePrice: 189,
    category: "boneless",
    piecesCount: 10,
    maxFlavorsAllowed: 2,
    imageUrl: "https://images.unsplash.com/photo-1562967914-608f82629710?q=80&w=800&auto=format&fit=crop",
    popular: true,
  },
  {
    id: "prod-boneless-15",
    name: "Boneless de Pechuga (15 Pzas)",
    slug: "boneless-15-piezas",
    description: "15 tiernos cubos de pechuga crujiente preparados al instante con hasta 2 salsas.",
    basePrice: 269,
    category: "boneless",
    piecesCount: 15,
    maxFlavorsAllowed: 2,
    imageUrl: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: "prod-boneless-20",
    name: "Boneless de Pechuga (20 Pzas)",
    slug: "boneless-20-piezas",
    description: "20 piezas de boneless premium para compartir con amigos, hasta 3 salsas combinables.",
    basePrice: 349,
    category: "boneless",
    piecesCount: 20,
    maxFlavorsAllowed: 3,
    imageUrl: "https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?q=80&w=800&auto=format&fit=crop",
    popular: true,
  },
  {
    id: "prod-tenders-4",
    name: "Crispy Tenders (4 Pzas)",
    slug: "crispy-tenders-4-piezas",
    description: "4 tiras gigantes de pechuga extra jugosas marinadas y empanizadas a mano.",
    basePrice: 169,
    category: "tenders",
    piecesCount: 4,
    maxFlavorsAllowed: 1,
    imageUrl: "https://images.unsplash.com/photo-1562967916-eb82221dfb92?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: "prod-combo-all-in-one",
    name: "Wingstop All-in-One Combo",
    slug: "wingstop-all-in-one-combo",
    description: "8 alitas o boneless + Papas sazonadas regulares + 1 aderezo ranch + 1 refresco de 600 ml.",
    basePrice: 259,
    category: "combos",
    piecesCount: 8,
    maxFlavorsAllowed: 2,
    imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=800&auto=format&fit=crop",
    isCombo: true,
    popular: true,
  },
  {
    id: "prod-combo-crew-pack",
    name: "Crew Pack (30 Piezas + 2 Papas)",
    slug: "crew-pack-30-piezas",
    description: "30 piezas a elegir (Alitas o Boneless), hasta 4 salsas, 2 órdenes de papas sazonadas grandes y 3 dips ranch.",
    basePrice: 629,
    category: "combos",
    piecesCount: 30,
    maxFlavorsAllowed: 4,
    imageUrl: "https://images.unsplash.com/photo-1514944298352-f43577d46816?q=80&w=800&auto=format&fit=crop",
    isCombo: true,
  },
  {
    id: "prod-papas-sazonadas",
    name: "Papas Fritas Sazonadas Wingstop",
    slug: "papas-fritas-sazonadas",
    description: "Papas corte natural sazonadas con nuestro blend secreto de azúcar morena y especias.",
    basePrice: 65,
    category: "papas",
    maxFlavorsAllowed: 0,
    imageUrl: "https://images.unsplash.com/photo-1576107232684-1279f3908594?q=80&w=800&auto=format&fit=crop",
  },
];
