import type { Flavor, Product, DipOption, SideOption, DrinkOption } from "@/types/shop";

export const FLAVORS: Flavor[] = [
  {
    id: "buffalo-brava",
    name: "Buffalo Brava",
    slug: "buffalo-brava",
    heatLevel: 3,
    description: "La salsa búfalo insignia de Loco Rooster con vinagre añejo, mantequilla y chile de árbol.",
    isDryRub: false,
    badge: "Clásica",
  },
  {
    id: "bbq-ahumada",
    name: "BBQ Ahumada",
    slug: "bbq-ahumada",
    heatLevel: 1,
    description: "Salsa barbacoa caramelizada con madera de manzano y azúcar morena.",
    isDryRub: false,
    badge: "Favorita",
  },
  {
    id: "lemon-pepper",
    name: "Lemon Pepper Rooster",
    slug: "lemon-pepper",
    heatLevel: 1,
    description: "Sazonador seco cítrico crujiente con toque de pimienta negra recién molida.",
    isDryRub: true,
    badge: "Más Vendido",
  },
  {
    id: "garlic-parmesan",
    name: "Garlic & Parmesan",
    slug: "garlic-parmesan",
    heatLevel: 0,
    description: "Mantequilla de ajo rostizado con auténtico queso parmesano.",
    isDryRub: true,
  },
  {
    id: "mango-habanero",
    name: "Mango Habanero Furia",
    slug: "mango-habanero",
    heatLevel: 4,
    description: "Puré de mango tropical con fuego salvaje de chile habanero yucateco.",
    isDryRub: false,
    badge: "Picosa Top",
  },
  {
    id: "loco-atomic",
    name: "Loco Atomic 🔥",
    slug: "loco-atomic",
    heatLevel: 5,
    description: "Nuestra salsa más extrema con extracto de chile fantasma y carolina reaper.",
    isDryRub: false,
    badge: "Nivel 5",
  },
];

export const DIPS: DipOption[] = [
  { id: "ranch", name: "Ranch Artesanal Hecho en Casa (2 oz)", price: 25 },
  { id: "blue-cheese", name: "Blue Cheese Cremoso (2 oz)", price: 29 },
  { id: "queso-cheddar", name: "Dip de Queso Cheddar Caliente", price: 32 },
  { id: "salsa-especial", name: "Salsa Secreta Loco Rooster", price: 25 },
];

export const SIDES: SideOption[] = [
  { id: "papas-sazonadas", name: "Papas Fritas Sazonadas Especiales", price: 65 },
  { id: "papas-queso-tocino", name: "Papas con Queso Cheddar y Tocino", price: 89 },
  { id: "aros-cebolla", name: "Aros de Cebolla Crujientes", price: 79 },
  { id: "veggie-sticks", name: "Bastones de Apio y Zanahoria", price: 39 },
];

export const DRINKS: DrinkOption[] = [
  { id: "coca-cola-600", name: "Coca-Cola Original 600 ml", price: 38 },
  { id: "coca-sin-azucar", name: "Coca-Cola Sin Azúcar 600 ml", price: 38 },
  { id: "sprite-600", name: "Sprite 600 ml", price: 38 },
  { id: "cerveza-artesanal", name: "Cerveza Corona Extra 355 ml", price: 55 },
];

export const PRODUCTS: Product[] = [
  // 3 Productos Principales Requeridos en Tarea 5
  {
    id: "prod-alitas-20",
    name: "ALITAS",
    slug: "alitas",
    description: "20 Alitas crujientes con salsa Buffalo o BBQ a elegir, porción de papas y dos bebidas.",
    basePrice: 389,
    category: "alitas",
    piecesCount: 20,
    maxFlavorsAllowed: 2,
    imageUrl: "https://images.unsplash.com/photo-1567620832903-9fc6debc209f?q=80&w=800&auto=format&fit=crop",
    popular: true,
  },
  {
    id: "prod-hamburguesas",
    name: "HAMBURGUESAS",
    slug: "hamburguesas",
    description: "Hamburguesa doble de res (300g), queso cheddar derretido, tocino crujiente, lechuga, tomate y salsa especial Loco Rooster.",
    basePrice: 229,
    category: "hamburguesas",
    maxFlavorsAllowed: 0,
    imageUrl: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?q=80&w=800&auto=format&fit=crop",
    popular: true,
  },
  {
    id: "prod-crispy-tenders",
    name: "CRISPY TENDERS",
    slug: "crispy-tenders",
    description: "6 Tenders crujientes de pechuga de pollo empanizados, porción de papas y una salsa a elegir.",
    basePrice: 219,
    category: "tenders",
    piecesCount: 6,
    maxFlavorsAllowed: 1,
    imageUrl: "https://images.unsplash.com/photo-1562967916-eb82221dfb92?q=80&w=800&auto=format&fit=crop",
    popular: true,
  },
  // Catálogo complementario por categorías
  {
    id: "prod-boneless-10",
    name: "BONELESS (10 PZAS)",
    slug: "boneless-10-piezas",
    description: "10 bocados de 100% pechuga de pollo empanizada y bañada en tus salsas preferidas. Cero huesos, puro sabor.",
    basePrice: 189,
    category: "boneless",
    piecesCount: 10,
    maxFlavorsAllowed: 2,
    imageUrl: "https://images.unsplash.com/photo-1562967914-608f82629710?q=80&w=800&auto=format&fit=crop",
    popular: true,
  },
  {
    id: "prod-boneless-20",
    name: "BONELESS (20 PZAS)",
    slug: "boneless-20-piezas",
    description: "20 piezas de pechuga crujiente para compartir con amigos, hasta 3 salsas combinables.",
    basePrice: 349,
    category: "boneless",
    piecesCount: 20,
    maxFlavorsAllowed: 3,
    imageUrl: "https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: "prod-mega-combo-rooster",
    name: "MEGA COMBO ROOSTER",
    slug: "mega-combo-rooster",
    description: "Alitas, Hamburguesa, Tenders y Papas. La combinación definitiva para compartir entre 3 y 4 personas.",
    basePrice: 389,
    category: "combos",
    piecesCount: 15,
    maxFlavorsAllowed: 3,
    imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=800&auto=format&fit=crop",
    isCombo: true,
    popular: true,
  },
  {
    id: "prod-papas-especiales",
    name: "PAPAS ROOSTER CON QUESO",
    slug: "papas-rooster-queso",
    description: "Papas fritas corte natural cubiertas de queso cheddar derretido, tocino crujiente y jalapeño.",
    basePrice: 89,
    category: "papas",
    maxFlavorsAllowed: 0,
    imageUrl: "https://images.unsplash.com/photo-1576107232684-1279f3908594?q=80&w=800&auto=format&fit=crop",
  },
];
